In [1]:
#Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Read Dataset

dataset = pd.read_csv('train.csv')

In [3]:
dataset.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
print(dataset.shape)

(20800, 5)


In [5]:
#Dropping the 'id' column

dataset.drop('id', axis=1, inplace=True)

In [6]:
dataset.head()

title              author  \
0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [7]:
#Finding null values if any

dataset.isnull().sum()

title      558
author    1957
text        39
label        0
dtype: int64

In [8]:
#Dropping NaN values beacuse they cannot be reshaped

dataset.dropna(inplace=True)

In [9]:
#Finding null values if any

dataset.isnull().sum()

title     0
author    0
text      0
label     0
dtype: int64

In [10]:
dataset.head()

title              author  \
0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [11]:
print(dataset.shape)

(18285, 4)


In [12]:
newsDataset = dataset.copy()
newsDataset.reset_index(inplace=True)

In [13]:
newsDataset.head()

index                                              title  \
0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2                  Why the Truth Might Get You Fired   
3      3  15 Civilians Killed In Single US Airstrike Hav...   
4      4  Iranian woman jailed for fictional unpublished...   

               author                                               text  \
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s Let...   
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...   
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...   
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...   
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...   

   label  
0      1  
1      0  
2      1  
3      1  
4      1

In [14]:
#Cleaning the dataset texts(news)

import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

[nltk_data] Downloading package stopwords to C:\Users\Tanay
[nltk_data]     Gandhi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [15]:
# Cleaning the news
corpus = []

for i in range(0,newsDataset .shape[0]):
    news = re.sub(pattern='[^a-zA-Z]', repl=' ', string=newsDataset.title[i])
    news = news.lower()
    news = news.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')
    news = [ps.stem(word) for word in news if not word in set(all_stopwords)]
    news = ' '.join(news)
    corpus.append(news)

In [16]:
print(corpus[0:20])

['hous dem aid even see comey letter jason chaffetz tweet', 'flynn hillari clinton big woman campu breitbart', 'truth might get fire', 'civilian kill singl us airstrik identifi', 'iranian woman jail fiction unpublish stori woman stone death adulteri', 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart', 'beno hamon win french socialist parti presidenti nomin new york time', 'back channel plan ukrain russia courtesi trump associ new york time', 'obama organ action partner soro link indivis disrupt trump agenda', 'bbc comedi sketch real housew isi caus outrag', 'russian research discov secret nazi militari base treasur hunter arctic photo', 'us offici see link trump russia', 'ye paid govern troll social media blog forum websit', 'major leagu soccer argentin find home success new york time', 'well fargo chief abruptli step new york time', 'anonym donor pay million releas everyon arrest dakota access pipelin', 'fbi close hillari', 'chuck todd

In [17]:
#Creating the Bag of Words model

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values

In [18]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:
print(y)

[1 0 1 ... 0 1 1]


In [20]:
#Splitting into train and dev sets

from sklearn.model_selection import train_test_split
X_train, X_dev, y_train, y_dev = train_test_split(X, y, test_size=0.20, random_state=0)

In [21]:
#After several experimentation, Logic Regression Model is best suited for the dataset

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [22]:
#Predicting the Dev set results

y_pred = classifier.predict(X_dev)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_dev.reshape(len(y_dev),1)),1))

[[1 0]
 [1 0]
 [1 1]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [23]:
#Making the Confusion Matrix

from sklearn.metrics import accuracy_score, precision_score, recall_score
accuracyScore = accuracy_score(y_dev, y_pred)
precisionScore = precision_score(y_dev, y_pred)
recallScore = recall_score(y_dev, y_pred)
print("---- Scores ----")
print("Accuracy score is: {}%".format(round(accuracyScore*100,2)))
print("Precision score is: {}".format(round(precisionScore,2)))
print("Recall score is: {}".format(round(recallScore,2)))

---- Scores ----
Accuracy score is: 92.4%
Precision score is: 0.88
Recall score is: 0.95


In [24]:
#Read Test Dataset

test_dataset = pd.read_csv('test.csv')

In [25]:
test_dataset.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [26]:
#Finding null values if any

dataset.isnull().sum()

title     0
author    0
text      0
label     0
dtype: int64

In [27]:
#Predicting values for the test set results

def fakeNews(input_news):
    input_news = re.sub(pattern='[^a-zA-Z]',repl=' ', string=input_news)
    input_news = input_news.lower()
    input_news = input_news.split()
    input_news = [word for word in input_news if not word in set(stopwords.words('english'))]
    ps = PorterStemmer()
    input_news = [ps.stem(word) for word in input_news]
    input_news = ' '.join(input_news)

    input_news = cv.transform([input_news]).toarray()
    output = classifier.predict(input_news)
    return output

In [28]:
# For generating random news and classifying it

from random import randint
for i in range (0,21):
    row_number = randint(0,test_dataset.title.shape[0]-1)
    input_news = test_dataset.title[row_number]

    print('News: {' , input_news, '}')
    if fakeNews(input_news):
      print('Prediction: FAKE News!\n')
    else:
      print('Prediction: REAL News!\n')

News: { CLAIM: Just Mentioning Brexit Causes Hate Crime, Parliament Committee Told }
Prediction: FAKE News!

News: { The Zika Virus Is Harmless. It Does Not Cause Birth Defects (Bill Gates Releasing GM Mosquitoes Anyway) }
Prediction: FAKE News!

News: { Universe is a hologram/virtual reality - But why? Could it be this? }
Prediction: FAKE News!

News: { Trump controlled by Mossad }
Prediction: FAKE News!

News: { ‘We the people’ against tyranny: Seven principles for free government }
Prediction: FAKE News!

News: { In a Late-Night Move, Russia Arrests a Top Economic Official in a Bribery Case - The New York Times }
Prediction: REAL News!

News: { WikiLeaks releases 26th batch of #PodestaEmails from Clinton campaign chair }
Prediction: FAKE News!

News: { JUST IN: FBI Reopens Hillary Clinton Email Probe }
Prediction: FAKE News!

News: { Former Paramount Pictures CEO Brad Grey Dies at 59 }
Prediction: FAKE News!

News: { Britain Resumes Sharing Bombing Intel With US After Leaks - Breitb