In [1]:
#Import Libraries

import numpy as np
import pandas as pd
import tensorflow as tf
from tabulate import tabulate

In [2]:
#Read Dataset

dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)
max_columns = len(X[0])

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
#Gender column needs to be encoded

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
#Geography column needs to be encoded

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [11]:
#Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [12]:
#Feature Scaling is needed to train the model

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
#Experimentation

table = [['Nodes in Layer 1', 'Nodes in Layer 2', 'Accuracy']]

from sklearn.metrics import accuracy_score
for i in range (4, max_columns+2):
    for j in range (4, i+1):
        ann = tf.keras.models.Sequential()
        ann.add(tf.keras.layers.Dense(units = i, activation = 'relu'))
        ann.add(tf.keras.layers.Dense(units = j, activation = 'relu'))
        ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))
        ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
        ann.fit(X_train, y_train, batch_size = 32, epochs = 20)
        y_pred = ann.predict(X_test)
        y_pred = (y_pred > 0.5)
        acc = accuracy_score(y_test, y_pred)
        table.append([i,j,acc])
        

Epoch 1/20
250/250 [==============================] - 1s 1ms/step - loss: 0.5499 - accuracy: 0.7880
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4943 - accuracy: 0.7905
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4634 - accuracy: 0.7958
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4463 - accuracy: 0.7964
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4367 - accuracy: 0.7967
Epoch 6/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4286 - accuracy: 0.7993
Epoch 7/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4226 - accuracy: 0.7995
Epoch 8/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4359 - accuracy: 0.7882
Epoch 9/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4254 - accuracy: 0.7947
Epoch 10/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4252 - accuracy: 0.7939

250/250 [==============================] - 0s 1ms/step - loss: 0.4735 - accuracy: 0.7962
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4352 - accuracy: 0.8115
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4384 - accuracy: 0.8083
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4113 - accuracy: 0.8149
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4115 - accuracy: 0.8182
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4061 - accuracy: 0.8221
Epoch 8/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4121 - accuracy: 0.8194
Epoch 9/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4124 - accuracy: 0.8218
Epoch 10/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3921 - accuracy: 0.8315
Epoch 11/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4040 - accuracy: 0.8254
Epoch 12/

250/250 [==============================] - 0s 2ms/step - loss: 0.4441 - accuracy: 0.7983
Epoch 4/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4382 - accuracy: 0.7971
Epoch 5/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4284 - accuracy: 0.8051
Epoch 6/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4257 - accuracy: 0.8081
Epoch 7/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4277 - accuracy: 0.8128
Epoch 8/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4185 - accuracy: 0.8166
Epoch 9/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4196 - accuracy: 0.8190
Epoch 10/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4158 - accuracy: 0.8232
Epoch 11/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4190 - accuracy: 0.8219
Epoch 12/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4053 - accuracy: 0.8298
Epoch 13

Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4261 - accuracy: 0.8103
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4165 - accuracy: 0.8144
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4005 - accuracy: 0.8268
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3946 - accuracy: 0.8309
Epoch 8/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3882 - accuracy: 0.8294
Epoch 9/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3823 - accuracy: 0.8312
Epoch 10/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3928 - accuracy: 0.8238
Epoch 11/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3809 - accuracy: 0.8345
Epoch 12/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3818 - accuracy: 0.8276
Epoch 13/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3796 - accuracy: 0.8

250/250 [==============================] - 0s 1ms/step - loss: 0.3914 - accuracy: 0.8268
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3935 - accuracy: 0.8379
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3740 - accuracy: 0.8417
Epoch 8/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3596 - accuracy: 0.8520
Epoch 9/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3412 - accuracy: 0.8629
Epoch 10/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3384 - accuracy: 0.8607
Epoch 11/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3527 - accuracy: 0.8509
Epoch 12/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3404 - accuracy: 0.8602
Epoch 13/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3350 - accuracy: 0.8569
Epoch 14/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3403 - accuracy: 0.8583
Epoch 

250/250 [==============================] - 0s 1ms/step - loss: 0.4114 - accuracy: 0.8272
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3961 - accuracy: 0.8311
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3940 - accuracy: 0.8380
Epoch 8/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3814 - accuracy: 0.8425
Epoch 9/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3771 - accuracy: 0.8432
Epoch 10/20
250/250 [==============================] - 0s 2ms/step - loss: 0.3723 - accuracy: 0.8449
Epoch 11/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3688 - accuracy: 0.8464
Epoch 12/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3676 - accuracy: 0.8459
Epoch 13/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3651 - accuracy: 0.8471
Epoch 14/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3568 - accuracy: 0.8533
Epoch 

Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3991 - accuracy: 0.8268
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3793 - accuracy: 0.8418
Epoch 8/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3691 - accuracy: 0.8481
Epoch 9/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3680 - accuracy: 0.8424
Epoch 10/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3519 - accuracy: 0.8518
Epoch 11/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3577 - accuracy: 0.8476
Epoch 12/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3636 - accuracy: 0.8472
Epoch 13/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3438 - accuracy: 0.8563
Epoch 14/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3542 - accuracy: 0.8502
Epoch 15/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3476 - accuracy: 0

250/250 [==============================] - 0s 1ms/step - loss: 0.3844 - accuracy: 0.8404
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3729 - accuracy: 0.8427
Epoch 8/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3663 - accuracy: 0.8485
Epoch 9/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3544 - accuracy: 0.8530
Epoch 10/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3608 - accuracy: 0.8503
Epoch 11/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3580 - accuracy: 0.8543
Epoch 12/20
250/250 [==============================] - 0s 2ms/step - loss: 0.3537 - accuracy: 0.8585: 0s - loss: 0.3401 - ac
Epoch 13/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3533 - accuracy: 0.8541
Epoch 14/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3531 - accuracy: 0.8618
Epoch 15/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3451 

250/250 [==============================] - 0s 1ms/step - loss: 0.3894 - accuracy: 0.8374
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3908 - accuracy: 0.8310
Epoch 8/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3797 - accuracy: 0.8380
Epoch 9/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3775 - accuracy: 0.8390
Epoch 10/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3815 - accuracy: 0.8327
Epoch 11/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3796 - accuracy: 0.8322
Epoch 12/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3653 - accuracy: 0.8456
Epoch 13/20
250/250 [==============================] - 0s 2ms/step - loss: 0.3616 - accuracy: 0.8469
Epoch 14/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3594 - accuracy: 0.8470
Epoch 15/20
250/250 [==============================] - 0s 1ms/step - loss: 0.3535 - accuracy: 0.8535
Epoch

In [15]:
print(tabulate(table))

----------------  ----------------  --------
Nodes in Layer 1  Nodes in Layer 2  Accuracy
4                 4                 0.838
5                 4                 0.8395
5                 5                 0.8415
6                 4                 0.857
6                 5                 0.861
6                 6                 0.861
7                 4                 0.8475
7                 5                 0.849
7                 6                 0.8575
7                 7                 0.8585
8                 4                 0.859
8                 5                 0.8615
8                 6                 0.8515
8                 7                 0.8525
8                 8                 0.852
9                 4                 0.8565
9                 5                 0.8635
9                 6                 0.8625
9                 7                 0.859
9                 8                 0.8645
9                 9                 0.8615
10             

In [16]:
#Building the ANN
#After several experimentation the 
#Number of Hidden Layers required for the dataset are 2
#Number of Nodes in Layer 1 are 7
#Number of Nodes in Layer 2 are 5

ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 7, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 5, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5694 - accuracy: 0.7987
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4680 - accuracy: 0.7963
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4398 - accuracy: 0.8016
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4445 - accuracy: 0.7882
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4266 - accuracy: 0.7958
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4223 - accuracy: 0.8079
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4090 - accuracy: 0.8175
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3947 - accuracy: 0.8349
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3996 - accuracy: 0.8256
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3801 - accura

250/250 [==============================] - 0s 1000us/step - loss: 0.3354 - accuracy: 0.8573
Epoch 82/100
250/250 [==============================] - 0s 951us/step - loss: 0.3280 - accuracy: 0.8624
Epoch 83/100
250/250 [==============================] - 0s 948us/step - loss: 0.3285 - accuracy: 0.8645
Epoch 84/100
250/250 [==============================] - 0s 982us/step - loss: 0.3308 - accuracy: 0.8620
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3389 - accuracy: 0.8556
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3373 - accuracy: 0.8617
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3319 - accuracy: 0.8633
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3281 - accuracy: 0.8610
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3292 - accuracy: 0.8587
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3262 - a

In [17]:
#Using our ANN model to predict if the customer with the following informations will leave the bank:

#Geography: France
#Credit Score: 600
#Gender: Male
#Age: 40 years old
#Tenure: 3 years
#Balance: $ 60000
#Number of Products: 2
#Does this customer have a credit card ? Yes
#Is this customer an Active Member: Yes
#Estimated Salary: $ 50000

#So, should we say goodbye to that customer ?

print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [18]:
#Predicting the Test set results

y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [19]:
#Making the Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
acc = accuracy_score(y_test, y_pred)
print("The Accuracy of the model is: ", acc)

[[1511   84]
 [ 195  210]]
The Accuracy of the model is:  0.8605
